{"components_names": [[0, "org.apache.commons.lang3.exception.exceptionutilstest$exceptionwithoutcause.exceptionutilstest$exceptionwithoutcause()"], [1, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_nested()"], [2, "org.apache.commons.lang3.stringutils.defaultstring(string)"], [3, "org.apache.commons.lang3.classutils.getshortclassname(string)"], [4, "org.apache.commons.lang3.exception.exceptionutils.removecommonframes(list;list)"], [5, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablecount_throwable()"], [6, "org.apache.commons.lang3.exception.exceptionutilstest.redeclarecheckedexception()"], [7, "org.apache.commons.lang3.exception.exceptionutils.printrootcausestacktrace(throwable)"], [8, "org.apache.commons.lang3.exception.exceptionutils.getthrowablelist(throwable)"], [9, "org.apache.commons.lang3.exception.exceptionutilstest.testwrapandunwrapthrowable()"], [10, "org.apache.commons.lang3.exception.exceptionutilstest$exceptionwithcause.exceptionutilstest$exceptionwithcause(throwable)"], [11, "org.apache.commons.lang3.exception.exceptionutilstest.exceptionutilstest()"], [12, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_null()"], [13, "org.apache.commons.lang3.exception.exceptionutils.exceptionutils_init()"], [14, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_withoutcause()"], [15, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_jdknocause()"], [16, "org.apache.commons.lang3.test.notvisibleexceptionfactory$notvisibleexception.notvisibleexceptionfactory$notvisibleexception(throwable;1)"], [17, "org.apache.commons.lang3.exception.exceptionutils.hascause(throwable;class)"], [18, "org.apache.commons.lang3.exception.exceptionutils.typeerasure(throwable)"], [19, "org.apache.commons.lang3.exception.exceptionutilstest.setup()"], [20, "org.apache.commons.lang3.test.notvisibleexceptionfactory$notvisibleexception.notvisibleexceptionfactory$notvisibleexception(throwable)"], [21, "org.apache.commons.lang3.exception.exceptionutils.getrootcause(throwable)"], [22, "org.apache.commons.lang3.exception.exceptionutilstest$exceptionwithcause.exceptionutilstest$exceptionwithcause(string;throwable)"], [23, "org.apache.commons.lang3.exception.exceptionutilstest$exceptionwithcause.setcause(throwable)"], [24, "org.apache.commons.lang3.exception.exceptionutilstest.createexceptionwithoutcause()"], [25, "org.apache.commons.lang3.exception.exceptionutilstest.testwrapandunwrapcheckedexception()"], [26, "org.apache.commons.lang3.test.notvisibleexceptionfactory$notvisibleexception.getcause()"], [27, "org.apache.commons.lang3.exception.exceptionutilstest$exceptionwithcause.getcause()"], [28, "org.apache.commons.lang3.exception.exceptionutils.wrapandthrow(throwable)"], [29, "org.apache.commons.lang3.exception.exceptionutils.indexof(throwable;class;int;boolean)"], [30, "org.apache.commons.lang3.exception.exceptionutilstest.throwscheckedexception()"], [31, "org.apache.commons.lang3.exception.exceptionutils.indexoftype(throwable;class)"], [32, "org.apache.commons.lang3.exception.exceptionutilstest$nestableexception.exceptionutilstest$nestableexception(throwable)"], [33, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_jdknocause()"], [34, "org.apache.commons.lang3.exception.exceptionutilstest$exceptionwithoutcause.exceptionutilstest$exceptionwithoutcause(1)"], [35, "org.apache.commons.lang3.exception.exceptionutilstest.testgetcause_throwablearray()"], [36, "org.apache.commons.lang3.exception.exceptionutils.rethrow(throwable)"], [37, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_withoutcause()"], [38, "org.apache.commons.lang3.exception.exceptionutilstest.testthrow()"], [39, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_recursivecause()"], [40, "org.apache.commons.lang3.exception.exceptionutils.getcauseusingmethodname(throwable;string)"], [41, "org.apache.commons.lang3.exception.exceptionutils.indexofthrowable(throwable;class;int)"], [42, "org.apache.commons.lang3.stringutils.isempty(charsequence)"], [43, "org.apache.commons.lang3.classutils.classutils_init()"], [44, "org.apache.commons.lang3.exception.exceptionutils.getrootcausemessage(throwable)"], [45, "org.apache.commons.lang3.classutils.getshortclassname(object;string)"], [46, "org.apache.commons.lang3.exception.exceptionutils.indexofthrowable(throwable;class)"], [47, "org.apache.commons.lang3.exception.exceptionutils.printrootcausestacktrace(throwable;printstream)"], [48, "org.apache.commons.lang3.exception.exceptionutils.getthrowablecount(throwable)"], [49, "org.apache.commons.lang3.exception.exceptionutils.getmessage(throwable)"], [50, "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_withcause()"], [51, "org.apache.commons.lang3.stringutils.defaultstring(string;string)"], [52, "org.apache.commons.lang3.exception.exceptionutils.getcause(throwable)"], [53, "org.apache.commons.lang3.test.notvisibleexceptionfactory.createexception(throwable)"], [54, "org.apache.commons.lang3.exception.exceptionutilstest$testthrowable.exceptionutilstest$testthrowable()"], [55, "org.apache.commons.lang3.exception.exceptionutils.getthrowables(throwable)"], [56, "org.apache.commons.lang3.exception.exceptionutils.getcause(throwable;string[])"], [57, "org.apache.commons.lang3.exception.exceptionutilstest.teardown()"], [58, "org.apache.commons.lang3.classutils.getshortclassname(class)"]], "initial_tests": ["org.apache.commons.lang3.exception.exceptionutilstest.testgetrootcause_throwable", "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_withcause", "org.apache.commons.lang3.exception.exceptionutilstest.testindexoftype_throwableclass", "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_recursivecause", "org.apache.commons.lang3.exception.exceptionutilstest.test_getmessage_throwable", "org.apache.commons.lang3.exception.exceptionutilstest.testconstructor", "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_nested", "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_null", "org.apache.commons.lang3.exception.exceptionutilstest.testindexof_throwableclassint", "org.apache.commons.lang3.exception.exceptionutilstest.testwrapandunwraperror", "org.apache.commons.lang3.exception.exceptionutilstest.testcatchtechniques", "org.apache.commons.lang3.exception.exceptionutilstest.testremovecommonframes_listlist", "org.apache.commons.lang3.exception.exceptionutilstest.testprintrootcausestacktrace_throwable", "org.apache.commons.lang3.exception.exceptionutilstest.test_getrootcausemessage_throwable", "org.apache.commons.lang3.exception.exceptionutilstest.testgetcause_throwable", "org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_withoutcause", "org.apache.commons.lang3.exception.exceptionutilstest.testindexof_throwableclass"], "bugs": ["org.apache.commons.lang3.exception.exceptionutils.getrootcause(throwable)"], "tests_details": [["org.apache.commons.lang3.exception.exceptionutilstest.testgetrootcause_throwable", [0, 8, 10, 11, 16, 19, 20, 21, 23, 24, 32, 34, 53, 57], 1], ["org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_withcause", [0, 8, 10, 11, 16, 19, 20, 23, 24, 27, 32, 34, 53, 55, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testindexoftype_throwableclass", [0, 8, 10, 11, 13, 16, 19, 20, 23, 24, 27, 29, 31, 32, 34, 53, 55, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_recursivecause", [0, 8, 10, 11, 16, 19, 20, 23, 24, 27, 32, 34, 53, 55, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.test_getmessage_throwable", [0, 2, 3, 10, 11, 16, 19, 20, 22, 23, 24, 32, 34, 42, 45, 49, 51, 53, 57, 58], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testconstructor", [0, 8, 9, 10, 11, 15, 16, 17, 19, 20, 23, 24, 25, 27, 28, 32, 34, 39, 50, 53, 54, 55, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_nested", [0, 1, 8, 10, 11, 12, 16, 18, 19, 20, 23, 24, 32, 33, 34, 36, 38, 53, 55, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowablelist_throwable_null", [0, 8, 10, 11, 16, 19, 20, 23, 24, 32, 34, 53, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testindexof_throwableclassint", [0, 5, 8, 10, 11, 14, 16, 19, 20, 23, 24, 27, 29, 32, 34, 35, 40, 41, 46, 48, 53, 55, 56, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testwrapandunwraperror", [0, 10, 11, 16, 17, 19, 20, 23, 24, 28, 32, 34, 53, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testcatchtechniques", [0, 6, 8, 10, 11, 16, 18, 19, 20, 23, 24, 30, 32, 34, 36, 48, 53, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testremovecommonframes_listlist", [0, 4, 10, 11, 16, 19, 20, 23, 24, 32, 34, 53, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testprintrootcausestacktrace_throwable", [0, 7, 10, 11, 16, 19, 20, 23, 24, 32, 34, 47, 53, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.test_getrootcausemessage_throwable", [0, 2, 3, 8, 10, 11, 16, 19, 20, 21, 22, 23, 24, 27, 32, 34, 42, 43, 44, 45, 49, 51, 53, 57, 58], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testgetcause_throwable", [0, 10, 11, 16, 19, 20, 23, 24, 26, 27, 32, 34, 40, 52, 53, 56, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testgetthrowables_throwable_withoutcause", [0, 8, 10, 11, 16, 19, 20, 23, 24, 32, 34, 37, 53, 57], 0], ["org.apache.commons.lang3.exception.exceptionutilstest.testindexof_throwableclass", [0, 8, 10, 11, 16, 19, 20, 23, 24, 27, 29, 32, 34, 46, 53, 55, 57], 0]]}